permalink: pretty

title: I failed the Turing test
email: albertoburgosplaza@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: albertoburgosp
github_username: albertoburgosplaza
date_format: "ordinal"

theme: minima

# Use the following plug-ins
plugins:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-redirect-from # Set up custom redirects
  - jekyll-seo-tag
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji # Github flavored emoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - .gitignore
  - .jekyll-cache/

whitelist:
  - jekyll-redirect-from
